In [1]:
import numpy as np
import pandas as pd
import yfinance as yf

from hw4_utility import *

# Q1

In [2]:
m1 = np.array([[4, 0, 0, 0],[6, 7, 0, 0],[9, 11, 1, 0],[5, 4, 1, 1]])
m2 = np.array([[2, 3, 1, 2],[-2, 4, -1, 5],[3, 7, 1.5, 1],[6, -9, 3, 7]])

for i, matrix in enumerate([m1, m2], start=1):
    print(f"Matrix {i}:")
    print(f"Symmetric:", check_symmetric(matrix))
    print(f"Singular:", check_singular(matrix))
    print(f"Positive Definite:", check_posdef(matrix))
    print("--------------------")

Matrix 1:
Symmetric: False
Singular: False
Positive Definite: False
--------------------
Matrix 2:
Symmetric: False
Singular: True
Positive Definite: False
--------------------


# Q2

### LU Factorization

In [3]:
A = np.array([[4, 1, 1, 1],[1, 3, -1, 1],[1, -1, 2, 0],[1, 1, 0, 2]], dtype=float)

if lu_conditions(A):
    print("LU factorization conditions satisfied.")
    L, U = lu_factorization(A)
    print("\nMatrix A:")
    print(A)
    print("\nLower Triangular Matrix L:")
    print(L)
    print("\nUpper Triangular Matrix U:")
    print(U)
    print("\n(LU):")
    print(L @ U)
    if np.allclose(A, L @ U):
        print("\nLU factorization verified.")
    else:
        print("\nLU factorization failed.")
else:
    print("LU factorization not possibl.e")

LU factorization conditions satisfied.

Matrix A:
[[ 4.  1.  1.  1.]
 [ 1.  3. -1.  1.]
 [ 1. -1.  2.  0.]
 [ 1.  1.  0.  2.]]

Lower Triangular Matrix L:
[[ 1.          0.          0.          0.        ]
 [ 0.25        1.          0.          0.        ]
 [ 0.25       -0.45454545  1.          0.        ]
 [ 0.25        0.27272727  0.07692308  1.        ]]

Upper Triangular Matrix U:
[[ 4.          1.          1.          1.        ]
 [ 0.          2.75       -1.25        0.75      ]
 [ 0.          0.          1.18181818  0.09090909]
 [ 0.          0.          0.          1.53846154]]

(LU):
[[ 4.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00  3.00000000e+00 -1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00 -1.00000000e+00  2.00000000e+00 -1.38777878e-17]
 [ 1.00000000e+00  1.00000000e+00  2.13504428e-18  2.00000000e+00]]

LU factorization verified.


### LDL^T Factorization

In [4]:
A = np.array([[4, 1, 1, 1],[1, 3, -1, 1],[1, -1, 2, 0],[1, 1, 0, 2]], dtype=float)

if ldlt_conditions(A):
    print("LDL^T conditions satisfied.")
    L, D = ldlt_factorization(A)
    print("\nMatrix A:")
    print(A)
    print("\nLower Triangular Matrix L:")
    print(L)
    print("\nDiagonal Matrix D:")
    print(D)
    print("\n(LDL^T):")
    print(L @ D @ L.T)
    if np.allclose(A, L @ D @ L.T):
        print("\nLDL^T factorization verified.")
    else:
        print("\nLDL^T factorization failed.")
else:
    print("LDL^T factorization not possible.")

LDL^T conditions satisfied.

Matrix A:
[[ 4.  1.  1.  1.]
 [ 1.  3. -1.  1.]
 [ 1. -1.  2.  0.]
 [ 1.  1.  0.  2.]]

Lower Triangular Matrix L:
[[ 1.          0.          0.          0.        ]
 [ 0.25        1.          0.          0.        ]
 [ 0.25       -0.45454545  1.          0.        ]
 [ 0.25        0.27272727  0.07692308  1.        ]]

Diagonal Matrix D:
[[4.         0.         0.         0.        ]
 [0.         2.75       0.         0.        ]
 [0.         0.         1.18181818 0.        ]
 [0.         0.         0.         1.53846154]]

(LDL^T):
[[ 4.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00  3.00000000e+00 -1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00 -1.00000000e+00  2.00000000e+00  2.13504428e-18]
 [ 1.00000000e+00  1.00000000e+00 -1.38777878e-17  2.00000000e+00]]

LDL^T factorization verified.


### Cholesky Decomposition

In [5]:
A = np.array([[4, 1, 1, 1],[1, 3, -1, 1],[1, -1, 2, 0],[1, 1, 0, 2]], dtype=float)

if cholesky_conditions(A):
    print("Cholesky conditions satisfied.")
    L = cholesky_factorization(A)
    print("\nMatrix A:")
    print(A)
    print("\nLower Triangular Matrix L:")
    print(L)
    print("\nTranspose of Lower Triangular Matrix L.T:")
    print(L.T)
    print("\n(L @ L.T):")
    print(L @ L.T)
    if np.allclose(A, L @ L.T):
        print("\nCholesky factorization verified.")
    else:
        print("\nCholesky factorization failed.")
else:
    print("Cholesky factorization not possible.")

Cholesky conditions satisfied.

Matrix A:
[[ 4.  1.  1.  1.]
 [ 1.  3. -1.  1.]
 [ 1. -1.  2.  0.]
 [ 1.  1.  0.  2.]]

Lower Triangular Matrix L:
[[ 2.          0.          0.          0.        ]
 [ 0.5         1.6583124   0.          0.        ]
 [ 0.5        -0.75377836  1.08711461  0.        ]
 [ 0.5         0.45226702  0.0836242   1.24034735]]

Transpose of Lower Triangular Matrix L.T:
[[ 2.          0.5         0.5         0.5       ]
 [ 0.          1.6583124  -0.75377836  0.45226702]
 [ 0.          0.          1.08711461  0.0836242 ]
 [ 0.          0.          0.          1.24034735]]

(L @ L.T):
[[ 4.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00  3.00000000e+00 -1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00 -1.00000000e+00  2.00000000e+00 -1.76741685e-17]
 [ 1.00000000e+00  1.00000000e+00 -1.76741685e-17  2.00000000e+00]]

Cholesky factorization verified.


# Q3

In [6]:
A = np.array([[1, 1, 0, 3],[2, 1, -1, 1],[3, -1, -1, 2],[-1, 2, 3, -1]], dtype=float)
B = np.array([8, 7, 14, -7], dtype=float)
B_systems = [B.copy()]

for i in range(len(B)):
    B2 = B.copy()
    B2[i] *= 1.01
    B_systems.append(B2)

In [7]:
print("Solutions via LU FACTORIZATION:")
print("================")
for i, b in enumerate(B_systems, start=1):
    try:
        X = solve_system(A, b)
        print(f"SYSTEM {i}:")
        print(f"RHS Vector B:{b}")
        print(f"Solution X:{X}\n")
    except ValueError as e:
        print(f"SYSTEM {i}: {e}\n")

Solutions via LU FACTORIZATION:
SYSTEM 1:
RHS Vector B:[ 8.  7. 14. -7.]
Solution X:[ 3. -1.  0.  2.]

SYSTEM 2:
RHS Vector B:[ 8.08  7.   14.   -7.  ]
Solution X:[ 2.98153846 -0.99384615  0.          2.03076923]

SYSTEM 3:
RHS Vector B:[ 8.    7.07 14.   -7.  ]
Solution X:[ 3.01435897 -0.96589744 -0.02333333  1.98384615]

SYSTEM 4:
RHS Vector B:[ 8.    7.   14.14 -7.  ]
Solution X:[ 3.04666667 -1.04666667  0.04666667  2.        ]

SYSTEM 5:
RHS Vector B:[ 8.    7.   14.   -7.07]
Solution X:[ 2.9874359  -1.00358974 -0.02333333  2.00538462]



In [8]:
print("Solutions via GAUSSIAN ELIMINATION:")
print("======================================")
for i, b in enumerate(B_systems, start=1):
    X = gaussian_elimination(A, b)
    print(f"SYSTEM {i}:")
    print(f"RHS Vector B:{b}")
    print(f"Solution X:{X}\n")

Solutions via GAUSSIAN ELIMINATION:
SYSTEM 1:
RHS Vector B:[ 8.  7. 14. -7.]
Solution X:[ 3. -1.  0.  2.]

SYSTEM 2:
RHS Vector B:[ 8.08  7.   14.   -7.  ]
Solution X:[ 2.98153846 -0.99384615  0.          2.03076923]

SYSTEM 3:
RHS Vector B:[ 8.    7.07 14.   -7.  ]
Solution X:[ 3.01435897 -0.96589744 -0.02333333  1.98384615]

SYSTEM 4:
RHS Vector B:[ 8.    7.   14.14 -7.  ]
Solution X:[ 3.04666667 -1.04666667  0.04666667  2.        ]

SYSTEM 5:
RHS Vector B:[ 8.    7.   14.   -7.07]
Solution X:[ 2.9874359  -1.00358974 -0.02333333  2.00538462]



In [9]:
n = A.shape[0]

decomposition_ops = (2 / 3) * n**3
substitution_ops = 5 * (2 * n**2)
lu_ops = decomposition_ops + substitution_ops

gaussian_ops = 5 * (2 / 3) * n**3

print(f"LU Decomposition Total Operations: {lu_ops:.2f}")
print(f"Gaussian Elimination Total Operations: {gaussian_ops:.2f}\n")

if lu_ops < gaussian_ops:
    print("LU decomposition is more efficient for solving multiple systems with the same matrix A.")
else:
    print("Gaussian elimination is more efficient for solving single systems.")

LU Decomposition Total Operations: 202.67
Gaussian Elimination Total Operations: 213.33

LU decomposition is more efficient for solving multiple systems with the same matrix A.


# Q4

In [10]:
def get_stock_data(tickers, start_date, end_date):
    data = {ticker: yf.download(ticker, start=start_date, end=end_date)['Adj Close'] for ticker in tickers}
    df = pd.concat(data, axis=1, join="inner")
    df.columns = tickers
    df = df.dropna(how="any")
    return df

def analyze_stock_pair(main_ticker, pair_ticker, start_date, end_date):
    tickers = [main_ticker, pair_ticker]
    prices = get_stock_data(tickers, start_date, end_date)
    returns = prices.pct_change().dropna()
    cov_matrix = returns.cov()
    
    if cholesky_conditions(cov_matrix):
        L = cholesky_factorization(cov_matrix.to_numpy())
        return cov_matrix, True, L
    else:
        return cov_matrix, False, None

start_date = "2024-01-02"
end_date = "2024-11-29"

main_ticker = "JPM"
pair_tickers = ["BAC", "XOM", "AAPL", "CVX"]

for pair_ticker in pair_tickers:
    print(f"\nPair: {main_ticker} and {pair_ticker}\n")
    cov_matrix, cholesky_possible, L = analyze_stock_pair(main_ticker, pair_ticker, start_date, end_date)
    print(f"Covariance Matrix:\n{cov_matrix}\n")
    print(f"Cholesky Decomposition Possible: {cholesky_possible}\n")
    
    if L is not None:
        print(f"Cholesky Factorization (L):\n{L}")
        print(f"\nReconstructed Covariance Matrix (L * L^T):\n{L @ L.T}")
        print(f"\nOriginal Covariance Matrix:\n{cov_matrix}")
        if np.allclose(cov_matrix.to_numpy(), L @ L.T):
            print("\nVerification Passed.")
        else:
            print("\nVerification Failed.")
        break


Pair: JPM and BAC



[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Covariance Matrix:
          JPM       BAC
JPM  0.000227  0.000162
BAC  0.000162  0.000212

Cholesky Decomposition Possible: True

Cholesky Factorization (L):
[[0.01508031 0.        ]
 [0.01076698 0.00980001]]

Reconstructed Covariance Matrix (L * L^T):
[[0.00022742 0.00016237]
 [0.00016237 0.00021197]]

Original Covariance Matrix:
          JPM       BAC
JPM  0.000227  0.000162
BAC  0.000162  0.000212

Verification Passed.


# Q5

In [11]:
A = np.array([[-4, 6],[3, 8]], dtype=float)
U, S, Vt = svd(A)

print("Original Matrix A:")
print(A)
print("\nU (Left Singular Vectors):")
print(U)
print("\nS (Singular Values):")
print(S)
print("\nVt (Right Singular Vectors - Transposed):")
print(Vt)

print("\n(U * S * Vt):")
print(U @ S @ Vt)

if np.allclose(A, U @ S @ Vt):
    print("\nVerification Passed.")
else:
    print("\nVerification Failed.")

Original Matrix A:
[[-4.  6.]
 [ 3.  8.]]

U (Left Singular Vectors):
[[ 0.6 -0.8]
 [ 0.8  0.6]]

S (Singular Values):
[[10.  0.]
 [ 0.  5.]]

Vt (Right Singular Vectors - Transposed):
[[0. 1.]
 [1. 0.]]

(U * S * Vt):
[[-4.  6.]
 [ 3.  8.]]

Verification Passed.


# Q6

In [12]:
A = np.array([[1, -1],[0,  1],[-1, 0]])

eigenvalues, eigenvectors, transformed_data = pca(A)

print("Original Matrix A:")
print(A)
print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)
print("\nPCA Extraction:")
print(transformed_data)

Original Matrix A:
[[ 1 -1]
 [ 0  1]
 [-1  0]]

Eigenvalues:
[1.         0.33333333]

Eigenvectors:
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

PCA Extraction:
[[ 1.41421356  0.        ]
 [-0.70710678  0.70710678]
 [-0.70710678 -0.70710678]]
