In [1]:
import numpy as np
from hw4_utility import *

# Q1

In [2]:
m1 = np.array([[4, 0, 0, 0],[6, 7, 0, 0],[9, 11, 1, 0],[5, 4, 1, 1]])
m2 = np.array([[2, 3, 1, 2],[-2, 4, -1, 5],[3, 7, 1.5, 1],[6, -9, 3, 7]])

for i, matrix in enumerate([m1, m2], start=1):
    symmetric, singular, positive_definite = check_matrix(matrix)
    print(f"Matrix {i}:")
    print(f"Symmetric: {symmetric}")
    print(f"Singular: {singular}")
    print(f"Positive Definite: {positive_definite}\n")

Matrix 1:
Symmetric: False
Singular: False
Positive Definite: True

Matrix 2:
Symmetric: False
Singular: True
Positive Definite: True



In [3]:
m1 = np.array([[4, 0, 0, 0],[6, 7, 0, 0],[9, 11, 1, 0],[5, 4, 1, 1]])
m2 = np.array([[2, 3, 1, 2],[-2, 4, -1, 5],[3, 7, 1.5, 1],[6, -9, 3, 7]])

for i, matrix in enumerate([m1, m2], start=1):
    symmetric, singular, positive_definite = check_matrix2(matrix)
    print(f"Matrix {i}:")
    print(f"Symmetric: {symmetric}")
    print(f"Singular: {singular}")
    print(f"Positive Definite: {positive_definite}\n")

Matrix 1:
Symmetric: False
Singular: False
Positive Definite: True

Matrix 2:
Symmetric: False
Singular: False
Positive Definite: True



# Q2

In [4]:
A = np.array([[4, 1, 1, 1],
              [1, 3, -1, 1],
              [1, -1, 2, 0],
              [1, 1, 0, 2]], dtype=float)

# Perform LU decomposition
L, U = lu_factorization(A)

print("Matrix A:")
print(A)
print("\nLower Triangular Matrix L:")
print(L)
print("\nUpper Triangular Matrix U:")
print(U)

# Verify LU decomposition
reconstructed_A = L @ U
print("\nReconstructed Matrix A (L @ U):")
print(reconstructed_A)

# Check if reconstruction matches the original matrix
if np.allclose(A, reconstructed_A):
    print("\nLU decomposition verified successfully!")
else:
    print("\nLU decomposition failed.")

Matrix A:
[[ 4.  1.  1.  1.]
 [ 1.  3. -1.  1.]
 [ 1. -1.  2.  0.]
 [ 1.  1.  0.  2.]]

Lower Triangular Matrix L:
[[ 1.          0.          0.          0.        ]
 [ 0.25        1.          0.          0.        ]
 [ 0.25       -0.45454545  1.          0.        ]
 [ 0.25        0.27272727  0.07692308  1.        ]]

Upper Triangular Matrix U:
[[ 4.          1.          1.          1.        ]
 [ 0.          2.75       -1.25        0.75      ]
 [ 0.          0.          1.18181818  0.09090909]
 [ 0.          0.          0.          1.53846154]]

Reconstructed Matrix A (L @ U):
[[ 4.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00  3.00000000e+00 -1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00 -1.00000000e+00  2.00000000e+00 -1.38777878e-17]
 [ 1.00000000e+00  1.00000000e+00  2.13504428e-18  2.00000000e+00]]

LU decomposition verified successfully!


In [ ]:
A = np.array([[4, 1, 1, 1],
              [1, 3, -1, 1],
              [1, -1, 2, 0],
              [1, 1, 0, 2]], dtype=float)

try:
    L, D = ldlt_factorization(A)
    print("Matrix A:")
    print(A)
    print("\nLower Triangular Matrix L:")
    print(L)
    print("\nDiagonal Matrix D:")
    print(D)
    
    # Verify LDLᵀ decomposition
    reconstructed_A = L @ D @ L.T
    print("\nReconstructed Matrix A (L @ D @ L.T):")
    print(reconstructed_A)
    
    if np.allclose(A, reconstructed_A):
        print("\nLDL^T factorization verified successfully!")
    else:
        print("\nLDL^T factorization failed.")
except ValueError as e:
    print(e)

Matrix A:
[[ 4.  1.  1.  1.]
 [ 1.  3. -1.  1.]
 [ 1. -1.  2.  0.]
 [ 1.  1.  0.  2.]]

Lower Triangular Matrix L:
[[ 1.          0.          0.          0.        ]
 [ 0.25        1.          0.          0.        ]
 [ 0.25       -0.45454545  1.          0.        ]
 [ 0.25        0.27272727  0.07692308  1.        ]]

Diagonal Matrix D:
[[4.         0.         0.         0.        ]
 [0.         2.75       0.         0.        ]
 [0.         0.         1.18181818 0.        ]
 [0.         0.         0.         1.53846154]]

Reconstructed Matrix A (L @ D @ L.T):
[[ 4.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00  3.00000000e+00 -1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00 -1.00000000e+00  2.00000000e+00  2.13504428e-18]
 [ 1.00000000e+00  1.00000000e+00 -1.38777878e-17  2.00000000e+00]]

LDLᵀ factorization verified successfully!


In [6]:
def cholesky_decomposition(A):
    n = A.shape[0]
    L = np.zeros_like(A)

    for i in range(n):
        # Compute diagonal element L[i, i]
        L[i, i] = np.sqrt(A[i, i] - sum(L[i, k] ** 2 for k in range(i)))
        
        # Compute off-diagonal elements L[j, i] for j > i
        for j in range(i + 1, n):
            L[j, i] = (A[j, i] - sum(L[j, k] * L[i, k] for k in range(i))) / L[i, i]

    return L

# Define the matrix
A = np.array([[4, 12, -16],
              [12, 37, -43],
              [-16, -43, 98]], dtype=float)

# Perform Cholesky decomposition
try:
    L = cholesky_decomposition(A)
    print("Matrix A:")
    print(A)
    print("\nLower Triangular Matrix L:")
    print(L)
    print("\nReconstructed Matrix A (L @ L.T):")
    print(L @ L.T)

    if np.allclose(A, L @ L.T):
        print("\nCholesky decomposition verified successfully!")
    else:
        print("\nCholesky decomposition failed.")
except ValueError as e:
    print(e)

Matrix A:
[[  4.  12. -16.]
 [ 12.  37. -43.]
 [-16. -43.  98.]]

Lower Triangular Matrix L:
[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]

Reconstructed Matrix A (L @ L.T):
[[  4.  12. -16.]
 [ 12.  37. -43.]
 [-16. -43.  98.]]

Cholesky decomposition verified successfully!


# Q3

# Q4

# Q5

# Q6